# Generated by Django 5.2.7 on 2025-11-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_custom_admin',
            field=models.BooleanField(default=False),
        ),
    ]
