# Generated by hand to add daily claim fields to PTCCurrency
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tags_and_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptccurrency',
            name='last_daily_claim',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ptccurrency',
            name='daily_streak',
            field=models.IntegerField(default=0),
        ),
    ]
