# Generated by Django 5.2.7 on 2025-12-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_tags_options_alter_tags_name_alter_tags_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
